# Generated by Django 5.1.5 on 2025-02-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_movie_cart_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='movie_object',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
